name: Change tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: rustup update && rustup target add aarch64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: '**/requirements.dev.txt'
      - run: pip install -r python/requirements.dev.txt
      - run: maturin build -m python/Cargo.toml --zig --compatibility manylinux2014 --target aarch64-unknown-linux-gnu --features abi3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/aarch64
      - run: docker run -v "$(pwd)":/workdir --platform linux/aarch64 quay.io/pypa/manylinux2014_aarch64 /bin/bash /workdir/.github/workflows/zig_test.sh
